package com.resumeflow.resume;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.resumeflow.resume.parser.SampleResumes;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

/**
 * Golden PDF tests against the real document processor, which must run on
 * the host at :8001 (the test JVM itself calls it, so plain localhost is
 * used — only PostgreSQL/Redis run in containers).
 *
 * <ul>
 *   <li>No-edit: generated bytes are byte-identical to the upload.</li>
 *   <li>Name change: only the intended element changes.</li>
 *   <li>Long bullet: overflow is reported, original kept, no redesign.</li>
 * </ul>
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Testcontainers
class GoldenPdfIT {

  @Container
  static final PostgreSQLContainer<?> POSTGRES =
      new PostgreSQLContainer<>("postgres:18-alpine");

  @Container
  static final GenericContainer<?> REDIS =
      new GenericContainer<>("redis:7-alpine").withExposedPorts(6379);

  @DynamicPropertySource
  static void properties(DynamicPropertyRegistry registry) {
    registry.add("spring.datasource.url", POSTGRES::getJdbcUrl);
    registry.add("spring.datasource.username", POSTGRES::getUsername);
    registry.add("spring.datasource.password", POSTGRES::getPassword);
    registry.add("spring.data.redis.host", REDIS::getHost);
    registry.add("spring.data.redis.port", () -> REDIS.getMappedPort(6379));
  }

  @LocalServerPort
  private int port;

  @Autowired
  private ObjectMapper objectMapper;

  private HttpClient http;
  private String base;

  @BeforeEach
  void setUp() {
    http = HttpClient.newHttpClient();
    base = "http://localhost:" + port + "/api/v1/resumes";
  }

  @Test
  void noEditKeepsOriginalBytes() throws Exception {
    Path tempDir = Files.createTempDirectory("resumeflow-golden-");
    byte[] original = Files.readAllBytes(SampleResumes.pdfSample(tempDir));
    String resumeId = upload(original, "resume.pdf", "application/pdf");

    postEmpty(base + "/" + resumeId + "/generate", 200);
    byte[] downloaded = getBytes(base + "/" + resumeId + "/download", 200);

    assertArrayEquals(original, downloaded);
  }

  @Test
  void nameChangeAffectsOnlyTheName() throws Exception {
    Path tempDir = Files.createTempDirectory("resumeflow-golden-");
    byte[] original = Files.readAllBytes(SampleResumes.pdfSample(tempDir));
    String resumeId = upload(original, "resume.pdf", "application/pdf");

    JsonNode editor = get(base + "/" + resumeId, 200);
    JsonNode content = ((tools.jackson.databind.node.ObjectNode) editor.get("content").deepCopy());
    ((tools.jackson.databind.node.ObjectNode) content.get("personal")).put("name", "ANA RAE");
    putJson(base + "/" + resumeId + "/content",
        objectMapper.writeValueAsString(Map.of(
            "expectedVersion", editor.get("resume").get("version").asLong(),
            "content", objectMapper.treeToValue(content, Object.class))),
        200);

    JsonNode generated = postEmpty(base + "/" + resumeId + "/generate", 200);
    assertTrue(generated.get("warnings").isEmpty(),
        "unexpected warnings: " + generated.get("warnings"));
    byte[] downloaded = getBytes(base + "/" + resumeId + "/download", 200);

    String text = extractText(downloaded);
    assertTrue(text.contains("ANA RAE"));
    assertFalse(text.contains("Maya Chen"));
    assertEquals(pageCount(original), pageCount(downloaded));
    for (String intact : List.of("Senior Product Engineer", "University of California, Davis",
        "TypeScript | React", "Led delivery")) {
      assertTrue(text.contains(intact), "content lost: " + intact);
    }
  }

  @Test
  void longBulletReportsOverflowAndKeepsOriginal() throws Exception {
    Path tempDir = Files.createTempDirectory("resumeflow-golden-");
    byte[] original = Files.readAllBytes(SampleResumes.pdfSample(tempDir));
    String resumeId = upload(original, "resume.pdf", "application/pdf");

    JsonNode editor = get(base + "/" + resumeId, 200);
    JsonNode content = ((tools.jackson.databind.node.ObjectNode) editor.get("content").deepCopy());
    var experience = (tools.jackson.databind.node.ArrayNode) content.get("experience");
    var bullets = (tools.jackson.databind.node.ArrayNode) experience.get(0).get("bullets");
    bullets.set(
        0,
        tools.jackson.databind.node.StringNode.valueOf(
            "Led delivery of a workflow platform that is far too long to fit inside "
                + "the original element and must therefore be reported instead of "
                + "silently redesigning the page layout."));
    putJson(base + "/" + resumeId + "/content",
        objectMapper.writeValueAsString(Map.of(
            "expectedVersion", editor.get("resume").get("version").asLong(),
            "content", objectMapper.treeToValue(content, Object.class))),
        200);

    JsonNode generated = postEmpty(base + "/" + resumeId + "/generate", 200);
    boolean overflow = false;
    for (JsonNode warning : generated.get("warnings")) {
      if (warning.asText().contains("overflow")) {
        overflow = true;
      }
    }
    assertTrue(overflow, "expected an overflow warning, got: " + generated.get("warnings"));

    byte[] downloaded = getBytes(base + "/" + resumeId + "/download", 200);
    String text = extractText(downloaded);
    assertTrue(text.contains("Built reusable commerce tools.")
        || text.contains("Led delivery"));
    assertEquals(pageCount(original), pageCount(downloaded));
  }

  private String upload(byte[] bytes, String filename, String mime) throws Exception {
    String boundary = "----golden" + System.nanoTime();
    List<byte[]> parts = new ArrayList<>();
    parts.add(("--" + boundary + "\r\n").getBytes(StandardCharsets.UTF_8));
    parts.add(("Content-Disposition: form-data; name=\"file\"; filename=\"" + filename
        + "\"\r\n").getBytes(StandardCharsets.UTF_8));
    parts.add(("Content-Type: " + mime + "\r\n\r\n").getBytes(StandardCharsets.UTF_8));
    parts.add(bytes);
    parts.add(("\r\n--" + boundary + "--\r\n").getBytes(StandardCharsets.UTF_8));
    int length = parts.stream().mapToInt(part -> part.length).sum();
    byte[] body = new byte[length];
    int offset = 0;
    for (byte[] part : parts) {
      System.arraycopy(part, 0, body, offset, part.length);
      offset += part.length;
    }
    HttpResponse<String> response = http.send(
        HttpRequest.newBuilder(URI.create(base))
            .POST(HttpRequest.BodyPublishers.ofByteArray(body))
            .header("Content-Type", "multipart/form-data; boundary=" + boundary)
            .build(),
        HttpResponse.BodyHandlers.ofString());
    assertEquals(201, response.statusCode(), response.body());
    return objectMapper.readTree(response.body()).get("resumeId").asText();
  }

  private JsonNode get(String url, int expected) throws Exception {
    HttpResponse<String> response = http.send(
        HttpRequest.newBuilder(URI.create(url)).GET().build(),
        HttpResponse.BodyHandlers.ofString());
    assertEquals(expected, response.statusCode(), response.body());
    return objectMapper.readTree(response.body());
  }

  private byte[] getBytes(String url, int expected) throws Exception {
    HttpResponse<byte[]> response = http.send(
        HttpRequest.newBuilder(URI.create(url)).GET().build(),
        HttpResponse.BodyHandlers.ofByteArray());
    assertEquals(expected, response.statusCode(), url);
    return response.body();
  }

  private JsonNode putJson(String url, String json, int expected) throws Exception {
    HttpResponse<String> response = http.send(
        HttpRequest.newBuilder(URI.create(url))
            .PUT(HttpRequest.BodyPublishers.ofString(json))
            .header("Content-Type", "application/json")
            .build(),
        HttpResponse.BodyHandlers.ofString());
    assertEquals(expected, response.statusCode(), response.body());
    return objectMapper.readTree(response.body());
  }

  private JsonNode postEmpty(String url, int expected) throws Exception {
    HttpResponse<String> response = http.send(
        HttpRequest.newBuilder(URI.create(url)).POST(HttpRequest.BodyPublishers.noBody()).build(),
        HttpResponse.BodyHandlers.ofString());
    assertEquals(expected, response.statusCode(), response.body());
    return objectMapper.readTree(response.body());
  }

  private static String extractText(byte[] pdf) throws Exception {
    try (PDDocument document = Loader.loadPDF(pdf)) {
      return new PDFTextStripper().getText(document);
    }
  }

  private static int pageCount(byte[] pdf) throws Exception {
    try (PDDocument document = Loader.loadPDF(pdf)) {
      return document.getNumberOfPages();
    }
  }
}
